name: Ping Streamlit App with Puppeteer

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: |
          npm init -y
          npm install puppeteer

      - name: Launch Headless Browser to Ping Streamlit
        run: |
          node wakeup.js
