name: Ping Streamlit App with Puppeteer

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer & Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxss1 \
            libappindicator1 \
            libindicator7 \
            libasound2 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            fonts-liberation \
            libgbm1 \
            libgtk-3-0 \
            libpango-1.0-0 \
            libcairo2 \
            libatspi2.0-0 \
            libdrm2 \
            libxkbcommon0 \
            libxshmfence1
          npm init -y
          npm install puppeteer

      - name: Run Puppeteer Script
        run: node wakeup.js
